### ISSUE TITLE
Not compiling to ESP8266 anymore

### ISSUE THREAD

**Issue by hraHoo** [cotestatnt/esp-fs-webserver#76]
All work in version 3.2.1 but now I get following error in Arduino IDE:

....\libraries\esp-fs-webserver\src\FSWebServer.cpp: In member function 'void FSWebServer::handleFileUpload()':
....\libraries\esp-fs-webserver\src\FSWebServer.cpp:552:33: error: 'class fs::File' has no member named 'path'
  552 |         if (strcmp(m_uploadFile.path(), ESP_FS_WS_CONFIG_FILE) == 0 && m_configSavedCallback) {
      |                                 ^~~~
....\libraries\esp-fs-webserver\src\FSWebServer.cpp:554:48: error: 'class fs::File' has no member named 'path'
  554 |             m_configSavedCallback(m_uploadFile.path());
      |                                                ^~~~

**Comment by cotestatnt** [comment]
My bad... it's been a while since I last used the ESP8266, and I missed checking the new release's code for these boards. I'll need to add a preprocessor directive to handle the ESP8266 specifically and use the right method.

Thanks for catching this bug.
